build:
  modules:
    - ecbuild/new
    - ninja
    - aec
    - netcdf4
  parallel: 64
  dependencies:
    - ecmwf/eckit@feature/eckit-geo
  dependency_branch: feature/eckit-geo
  cmake_options:
    - -DENABLE_ECKIT_GEO=1
    - -DENABLE_EXTRA_TESTS=1
  force_build: true
  env:
    - ECCODES_ECKIT_GEO=1
  compiler_cc: gcc
  compiler_cxx: g++
  compiler_fc: gfortran
