name: reusable-ci-hpc

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string
      nightly_test:
        required: false
        type: boolean
        default: false

jobs:
  ci-hpc:
    name: ci-hpc
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-hpc.yml@v2
    with:
      name-prefix: eccodes-
      build-inputs: |
        --package: ${{ inputs.eccodes || 'ecmwf/eccodes@develop' }}
        --modules: |
          ecbuild
          ninja
          aec
        --parallel: 64
        ${{ inputs.nightly_test && '--post-script: .github/ci-nightly-test.sh' }}
    secrets: inherit
